maintainer        "Jose Diaz-Gonzalez"
maintainer_email  "chefsen@josediazgonzalez.com"
license           "MIT"
description       "Install nodejs"
version           "1.0.0"
supports          "mac_os_x"
depends           "chef-homebrew"
